### ISSUE TITLE
null cannot be cast to non-null type net.corda.core.identity.Party error

### ISSUE THREAD

**Issue by PronoyC** [oraclize/corda-api#1]
The call serviceHub.identityService.wellKnownPartyFromX500Name(OraclizeUtils.getNodeName()) on line 36 in OraclizeQueryAwaitFlow.kt returns null and it wants to be casted as a Party, but it is not possible, throwing a TypeCastException. I believe adding "as?" instead of "as" should solve the problem.

**Comment by gitmp01** [comment]
Did you load the Cordapp on the public testnet? If not, that could be the problem because the `identityService` couldn't reach our public node. We are currently working on a tool for testing on private networks, but in the meantime, you should load you're cordapp on a node connected to the public testnet.
